import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="bg-neutral-950 text-white p-5 h-24 flex items-center justify-between z-10 relative">
          <Link href="/">My Properties</Link>
          <ul className="flex gap-6 items-center">
            <li>
              <Link href="/signin">Signin</Link>
            </li>
             <li>
              <Link href="/signup">Signup</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
