import AuthButtons from "@/components/auth-buttons";
import { AuthProvider } from "@/context/auth";
import { HomeIcon } from "lucide-react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} } antialiased`}>
        <AuthProvider>
          <nav className="p-4 flex items-center justify-between h-24 sticky top-0 bg-background z-10">
            <Link
              href="/"
              className="text-2xl tracking-widest flex gap-2 items-center uppercase"
            >
              <HomeIcon size={40} />
              <span>My properties</span>
            </Link>
            <ul className="flex gap-6 items-center">
              <li>
                <Link
                  href="/property-search"
                  className="uppercase tracking-widest hover:underline"
                >
                  Property search
                </Link>
              </li>
              <li>
                <AuthButtons />
              </li>
            </ul>
          </nav>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
